version: "3.8"

services:
  pgsql:
    container_name: pgsql-app
    image: "postgres:latest"
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "./data:/var/lib/postgresql/data"
    restart: always

  adminer:
    container_name: adminer-app
    image: adminer
    ports:
      - "${ADMINER_PORT:-8000}:8080"
    restart: always
    depends_on:
      - pgsql
